// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcuiuubbaozcmejzvxje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjdWl1dWJiYW96Y21lanp2eGplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTI0NTcsImV4cCI6MjA2MjQ2ODQ1N30.83SOY3Svfi5e0IalJ4CYGo08gQYELxl7xG2y-pmz0Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});